name: Syntax Check

on:
  push:
    branches:
      - main

jobs:
  check-syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run syntax check
        run: |
          echo "Checking for syntax errors..."
          # Example: Simulates a syntax check
          echo "No syntax errors found!"